const {chromium}=require('C:/Users/nechanicky/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const {pathToFileURL}=require('url');
const path=require('path');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({viewport:{width:1100,height:950}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.join(__dirname,'index.html')).href);
 await page.waitForSelector('.phone');
 if(await page.locator('.step-button').count()!==6)throw Error('Step count');
 await page.getByRole('button',{name:'Hledat',exact:false}).click();
 await page.getByRole('button',{name:'Koupit',exact:false}).click();
 await page.getByRole('button',{name:'Slevové průkazy',exact:false}).click();
 await page.locator('[data-discount="ISIC"]').check();
 await page.locator('[data-action="add-passenger"]').click();
 await page.locator('[data-add="child"]').click();
 if(await page.locator('.added-passenger').count()!==1)throw Error('Passenger add');
 await page.getByRole('button',{name:'Nabídka jízdného',exact:false}).click();
 await page.locator('[data-fare="day"]').click();
 await page.getByRole('button',{name:'Souhrn jízdenek',exact:false}).click();
 await page.locator('[data-addon="dog"]').click();
 await page.locator('.bottom-action[data-step="payment"]').click();
 await page.locator('[data-payment="card"]').click();
 await page.locator('#terms').uncheck();
 await page.locator('[data-action="pay"]').click();
 if(!((await page.locator('#toast').textContent())||'').includes('smluvní podmínky'))throw Error('Terms validation');
 await page.screenshot({path:path.join(__dirname,'qa-desktop.png'),fullPage:true});
 await page.locator('[data-step="search"]').click();
 await page.setViewportSize({width:390,height:844});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth))throw Error('Mobile overflow');
 await page.screenshot({path:path.join(__dirname,'qa-mobile.png')});
 if(errors.length)throw Error(errors.join('\n'));
 console.log('PASS: 6 steps, search, purchase entry, discounts, passenger add, fare, addons, payment validation, desktop and 390px layout.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
